name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout thecyberhub-desktop code
        uses: actions/checkout@v2

      - name: Checkout thecyberhub gh-pages code
        uses: actions/checkout@v2
        with:
          repository: th3cyb3rhub/TheCyberHUB  # Replace with your GitHub username and repo name
          ref: gh-pages  # Check out the gh-pages branch
          path: gh-pages  # Place the contents in a 'gh-pages' directory

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Clear Electron Builder Cache
        run: rm -rf $HOME/.cache/electron-builder  # Clear the cache to prevent conflicts

      - name: Copy TheCyberHUB build files
        run: |
          mkdir -p dist  # Create the dist directory if it doesn't exist
          cp -R gh-pages/* ./  # Copy files from the 'gh-pages' directory to the current working directory
          # Optionally, you can specify specific files to copy, e.g.:
          # cp -R gh-pages/index.html ./  # Adjust this as needed

      - name: Install dependencies
        run: npm install

      - name: Package the app
        run: npm run package  # Ensure your dist script is set up correctly in package.json

      - name: Upload Release Assets
        uses: ncipollo/release-action@v1
        with:
          tag: 'v${{ github.run_number }}'
          files: |
            dist/mac/*.dmg  # Adjust this to your actual build output
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Make the token available in the environment
