name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Clone the gh-pages branch
        run: |
          git clone --single-branch --branch gh-pages https://github.com/th3cyb3rhub/TheCyberHUB.git temp
          # List the contents of the temp directory to verify files are present
          Get-ChildItem temp
          
          # Check if the target folder exists and remove if necessary
          if (Test-Path ".github") {
              Remove-Item -Recurse -Force ".github"
          }
          # Create the dist directory if it doesn't exist
          if (-Not (Test-Path "dist")) {
              New-Item -ItemType Directory -Path "dist"
          }

          # Copy necessary files into the dist directory
          Copy-Item -Recurse -Path "temp/*" -Destination "dist" -Force

      - name: Update paths in HTML and JS files
        run: |
          # Update paths in HTML files
          Get-ChildItem dist\*.html | ForEach-Object {
              (Get-Content $_.FullName) `
                  -replace 'src="(/assets/)', 'src="./assets/' `
                  -replace 'href="(/assets/)', 'href="./assets/' | Set-Content $_.FullName
          }
          
          # Update paths in JS files inside the assets folder
          Get-ChildItem dist\assets\*.js | ForEach-Object {
              (Get-Content $_.FullName) `
                  -replace '("/assets/)', '("./assets/' | Set-Content $_.FullName
          }

      - name: List files in the dist directory after copying
        run: |
          Get-ChildItem dist

      - name: Clear Electron Builder Cache
        run: |
          if (Test-Path "$HOME\.cache\electron-builder") {
              Remove-Item -Recurse -Force "$HOME\.cache\electron-builder"
          }

      - name: Install dependencies
        run: npm install

      - name: Package the app for Windows
        run: |
          npx electron-builder --win nsis -p never
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Release Assets
        uses: ncipollo/release-action@v1
        with:
          tag: 'v${{ github.run_number }}'
          name: 'TheCyberHUB Desktop Release v${{ github.run_number }}'
          artifacts: |
            dist/*.exe
          token: ${{ secrets.PAT_TOKEN }}  # Use your PAT here
          skipIfReleaseExists: true

      - name: Cleanup
        run: |
          echo "Cleaning up build artifacts"
          Remove-Item -Recurse -Force dist/*
