name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout thecyberhub-desktop code
        uses: actions/checkout@v2

      - name: Checkout thecyberhub gh-pages code
        uses: actions/checkout@v2
        with:
          repository: th3cyb3rhub/TheCyberHUB  # Replace with your GitHub username and repo name
          ref: gh-pages  # Check out the gh-pages branch
          path: ./  # Place it in a directory called 'thecyberhub'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Copy thecyberhub build files
        run: |
          mkdir dist
          cp -R * ./dist  # Copy files from the 'thecyberhub' directory to the current working directory

      - name: Build the Electron app
        run: npm run build  # Ensure your build script is set up correctly in package.json

      - name: Package the app
        run: npm run dist  # Ensure your dist script is set up correctly in package.json

      - name: Upload Release Assets
        uses: ncipollo/release-action@v1
        with:
          tag: 'v${{ github.run_number }}'
          files: |
            dist/mac/*.dmg  # Adjust this to your actual build output
